#!/bin/bash -e

cd ${OPUS_SOURCES_PATH}

ANDROID_TARGET_API=$1
ANDROID_TARGET_ABI=$2
OUTPUT_PATH=${WORK_PATH}/opus_1.5.2_${ANDROID_TARGET_ABI}

make .. \
  -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake \
  -DANDROID_ABI=$ANDROID_TARGET_ABI \
  -DANDROID_PLATFORM=android-$ANDROID_TARGET_API \
  -DOPUS_BUILD_SHARED_LIBRARY=ON \
  -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=$OUTPUT_PATH


cmake --build .
