#include <pj/config_site_sample.h>
#define PJ_CONFIG_ANDROID 1
// #define PJMEDIA_HAS_VIDEO 1
// #define PJMEDIA_HAS_AND_MEDIA_AMRNB 1
// #define PJMEDIA_HAS_AND_MEDIA_AMRWB 1
// #define PJMEDIA_HAS_AND_MEDIA_H264 1
// #define PJMEDIA_HAS_AND_MEDIA_VP8 1
// #define PJMEDIA_HAS_AND_MEDIA_VP9 1
// #define PJMEDIA_HAS_ANDROID_MEDIACODEC 1

#define PJMEDIA_HAS_ILBC_CODEC 1
#define PJMEDIA_HAS_G722_CODEC 1
// #define PJMEDIA_HAS_GSM_CODEC 1
#define PJMEDIA_HAS_G729_CODEC 1
// #define PJMEDIA_HAS_OPUS_CODEC 1