services:
  pjsip-android:
    platform: linux/amd64
    build:
      context: . # Path to your Dockerfile
      dockerfile: Dockerfile # Name of your Dockerfile
      args:
        TZ: America/New_York
    image: ghcr.io/telebroad/pjsip-android-docker/build-pjsip-android:local # Name of the image to build
    container_name: build-pjsip-android # Name of the container
    volumes:
      - ./build:/pjsip/build # Mount local 'build' directory to 'pjsip/build' in the container
    environment:
      - TZ=America/New_York
      - CFLAGS=-g
