services:
  pjsip-android:
    platform: linux/amd64
    build:
      context: . # Path to your Dockerfile
      dockerfile: Dockerfile # Name of your Dockerfile
      args:
        TZ: America/New_York
        PJSIP_VERSION: 2.15.1 # to run a spesific release use master or tags/2.15.1 or anythink that can go in git checkout ${PJSIP_VERSION}
        CONF_DEBUG: false
    image: hub.deploy.telebroad.com/pjsip-android-docker:latest # Name of the image to build
    container_name: pjsip-android-docker # Name of the container
    volumes:
      - ./build:/pjsip/build # Mount local 'build' directory to 'pjsip/build' in the container
    environment:
      - TZ=America/New_York
      - CFLAGS=-g
