version: '3.8'

services:
  pjsip:
    build:
      context: .  # Path to your Dockerfile
      dockerfile: Dockerfile  # Name of your Dockerfile
    image: pjsip-docker:latest  # Name of the image to build
    container_name: pjsip-docker  # Name of the container
    volumes:
      - ./data:/pjsip/data  # Mount local 'data' directory to 'data' in the container
      - ./build:/pjsip/build
    environment:
      - SERVER_PORT=8080

